# Generated by Django 2.2 on 2019-04-28 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='solution',
            field=models.CharField(default='Solution', max_length=7),
        ),
        migrations.AddField(
            model_name='blog',
            name='solution_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
