# Generated by Django 2.2 on 2019-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190428_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='Timelimit: 1', max_length=50),
        ),
    ]
