# Generated by Django 2.2 on 2019-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190428_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.CharField(default='Timelimit: 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
