# Generated by Django 2.2 on 2019-04-29 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190428_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='solution_description',
            new_name='solution_c',
        ),
        migrations.AddField(
            model_name='blog',
            name='solution_java',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
