# Generated by Django 2.2 on 2019-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190429_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='submit',
            field=models.CharField(default='https://www.urionlinejudge.com.br/judge/en/runs/add/', max_length=150),
        ),
    ]
